[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_reports = ["SageNetCore", "SageNetReview"]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
educhaintestnet = "${EDUCHAIN_TESTNET_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
