[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
gas_reports = ["SageNetCore", "SageNetReview"]

fs_permissions = [{ access = "read", path = ".env"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
educhaintestnet = "${EDUCHAIN_TESTNET_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
